name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: 'github'
      - name: Build
        run: mvn clean install
        env:
          GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: 'github'
      - name: Deploy
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}
